#!/usr/bin/env bash
set -euo pipefail

ASR_URL="${ASR_URL:-http://127.0.0.1:8091/v1/asr/transcribe}"
ASR_LANGUAGE="${ASR_LANGUAGE:-auto}"
TTS_BASE_URL="${TTS_BASE_URL:-http://127.0.0.1:50000}"
TTS_MODE="${TTS_MODE:-sft}"
TTS_SPK_ID="${TTS_SPK_ID:-中文女}"
TTS_INSTRUCT_TEXT="${TTS_INSTRUCT_TEXT:-}"
TTS_SOURCE_RATE="${TTS_SOURCE_RATE:-22050}"
AGENTD_ADDR="${AGENTD_ADDR:-:8080}"

export AGENT_SERVER_ADDR="${AGENTD_ADDR}"
export AGENT_SERVER_VOICE_PROVIDER="funasr_http"
export AGENT_SERVER_VOICE_ASR_URL="${ASR_URL}"
export AGENT_SERVER_VOICE_ASR_LANGUAGE="${ASR_LANGUAGE}"
export AGENT_SERVER_VOICE_EMIT_PLACEHOLDER_AUDIO="false"
export AGENT_SERVER_TTS_PROVIDER="cosyvoice_http"
export AGENT_SERVER_TTS_COSYVOICE_BASE_URL="${TTS_BASE_URL}"
export AGENT_SERVER_TTS_COSYVOICE_MODE="${TTS_MODE}"
export AGENT_SERVER_TTS_COSYVOICE_SPK_ID="${TTS_SPK_ID}"
export AGENT_SERVER_TTS_COSYVOICE_INSTRUCT_TEXT="${TTS_INSTRUCT_TEXT}"
export AGENT_SERVER_TTS_COSYVOICE_SOURCE_SAMPLE_RATE="${TTS_SOURCE_RATE}"

exec go run ./cmd/agentd
