#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BINARY_PATH="${AGENT_SERVER_BINARY:-$REPO_ROOT/bin/agentd}"

if [[ ! -x "$BINARY_PATH" ]]; then
  echo "agentd binary not found at $BINARY_PATH; build it first" >&2
  exit 1
fi

export AGENT_SERVER_ADDR="${AGENT_SERVER_ADDR:-0.0.0.0:8080}"
export AGENT_SERVER_VOICE_PROVIDER="${AGENT_SERVER_VOICE_PROVIDER:-funasr_http}"
export AGENT_SERVER_VOICE_ASR_URL="${AGENT_SERVER_VOICE_ASR_URL:-http://127.0.0.1:8091/v1/asr/transcribe}"
export AGENT_SERVER_VOICE_ASR_LANGUAGE="${AGENT_SERVER_VOICE_ASR_LANGUAGE:-auto}"
export AGENT_SERVER_VOICE_EMIT_PLACEHOLDER_AUDIO="${AGENT_SERVER_VOICE_EMIT_PLACEHOLDER_AUDIO:-false}"
export AGENT_SERVER_VOICE_BARGE_IN_MIN_AUDIO_MS="${AGENT_SERVER_VOICE_BARGE_IN_MIN_AUDIO_MS:-120}"
export AGENT_SERVER_VOICE_BARGE_IN_HOLD_AUDIO_MS="${AGENT_SERVER_VOICE_BARGE_IN_HOLD_AUDIO_MS:-240}"
export AGENT_SERVER_VOICE_SPEECH_PLANNER_ENABLED="${AGENT_SERVER_VOICE_SPEECH_PLANNER_ENABLED:-true}"
export AGENT_SERVER_VOICE_SPEECH_PLANNER_MIN_CHUNK_RUNES="${AGENT_SERVER_VOICE_SPEECH_PLANNER_MIN_CHUNK_RUNES:-6}"
export AGENT_SERVER_VOICE_SPEECH_PLANNER_TARGET_CHUNK_RUNES="${AGENT_SERVER_VOICE_SPEECH_PLANNER_TARGET_CHUNK_RUNES:-24}"
export AGENT_SERVER_TTS_PROVIDER="${AGENT_SERVER_TTS_PROVIDER:-none}"
export AGENT_SERVER_AGENT_LLM_PROVIDER="${AGENT_SERVER_AGENT_LLM_PROVIDER:-bootstrap}"

cd "$REPO_ROOT"
exec "$BINARY_PATH"
