#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${FUNASR_PYTHON_BIN:-/home/ubuntu/miniconda3/envs/xiaozhi-esp32-server/bin/python}"

export PYTHONPATH="${PYTHONPATH:-$REPO_ROOT/workers/python/src}"
export AGENT_SERVER_FUNASR_HOST="${AGENT_SERVER_FUNASR_HOST:-127.0.0.1}"
export AGENT_SERVER_FUNASR_PORT="${AGENT_SERVER_FUNASR_PORT:-8091}"
export AGENT_SERVER_FUNASR_MODEL="${AGENT_SERVER_FUNASR_MODEL:-iic/SenseVoiceSmall}"
export AGENT_SERVER_FUNASR_DEVICE="${AGENT_SERVER_FUNASR_DEVICE:-cpu}"
export AGENT_SERVER_FUNASR_LANGUAGE="${AGENT_SERVER_FUNASR_LANGUAGE:-auto}"
export AGENT_SERVER_FUNASR_DISABLE_UPDATE="${AGENT_SERVER_FUNASR_DISABLE_UPDATE:-true}"
export AGENT_SERVER_FUNASR_TRUST_REMOTE_CODE="${AGENT_SERVER_FUNASR_TRUST_REMOTE_CODE:-false}"
export AGENT_SERVER_FUNASR_USE_ITN="${AGENT_SERVER_FUNASR_USE_ITN:-true}"

cd "$REPO_ROOT"
exec "$PYTHON_BIN" -m agent_server_workers.funasr_service
